#!/usr/bin/env bash

# (c) /u/supert 2016
# released under MIT licence

# script to print various info on state of fees in mempool and network

test -z $(which bitcoin-cli) && echo "$(basename $0) requires bitcoin-cli to be installed."
test -z $(which jq) && echo "$(basename $0) requires jq to be installed."
test -z $(which bc) && echo "$(basename $0) requires bc to be installed."

# test for options
HTML=
while getopts hwn: opt
do
    case "$opt" in
    (h) echo "usage: $0 [-w] [-n NUMBLOCKS]";;
    (w) HTML=1;;
    # n argument is number of blocks to show, default 10
    (n) NUMBLOCKS=${OPTARG-5};;
    esac
done

# fees in mempool
FEETOTAL=$(bitcoin-cli getrawmempool true | jq -r '.[]|.fee' | awk '{s+=$1} END {print s}' ) 

BTCUSD=$(curl -s "https://api.bitcoinaverage.com/ticker/USD/last")

echo "Fees in mempool: $FEETOTAL BTC, $(echo $FEETOTAL*$BTCUSD | bc) USD"
ESTIMATE=$(bitcoin-cli estimatefee 2)

# fee estimates
echo "estimated fee for inclusion in 2 blocks: $ESTIMATE BTC, $(echo $ESTIMATE*$BTCUSD | bc) USD, BTCUSD=\$$BTCUSD"

echo "tx in mempool: " $(bitcoin-cli getmempoolinfo | jq '.size') ", usage:" $(($(bitcoin-cli getmempoolinfo | jq '.usage') /1024/1024)) " Mb, size:" $(($(bitcoin-cli getmempoolinfo | jq '.bytes') /1024/1024)) " Mb"
