#!/usr/bin/env bash

# (c) /u/supert 2016
# released under MIT licence

# script to print various info on state of fees in mempool and network

# this will obviously need changing depending on block height
BLOCKREWARD=25

source script_functions

# test for options
HTML=
while getopts hwn: opt
do
    case "$opt" in
    (h) echo "usage: $0 [-w] [-n NUMBLOCKS]";;
    (w) HTML=1;;
    # n argument is number of blocks to show, default 10
    (n) NUMBLOCKS=${OPTARG-5};;
    esac
done

# market price
BTCUSD=$(curl -s "https://api.bitcoinaverage.com/ticker/USD/last")
echo "1 BTC = $BTCUSD USD"

# fees in mempool
FEETOTAL=$(bitcoin-cli getrawmempool true | jq -r '.[]|.fee' | awk '{s+=$1} END {print s}' ) 
FEES=$(printf "%.2f" $(echo $FEETOTAL*$BTCUSD | bc))
echo "Fees in mempool: $FEETOTAL BTC, $FEES USD"

RELAYFEE=$(printf "%.8f" $(bitcoin-cli getinfo | jq -r '.relayfee'))
LASTHASH=$(bitcoin-cli getbestblockhash)
TXCOUNT=$(bitcoin-cli getblock $LASTHASH | jq '.tx' | wc -l)
COINBASE=$(get_tx_fee $(bitcoin-cli getblock $LASTHASH | jq -r '.tx | .[]' | head -n1) | jq '.value' )
echo "Relay fee:" $RELAYFEE "BTC," $(printf "%.3f" $(echo $RELAYFEE*$BTCUSD | bc -l)) "USD"
echo "Average fees in last block:" $(printf "%.8f" $(echo "($COINBASE - $BLOCKREWARD) / $TXCOUNT " | bc -l)) "BTC, " $(printf "%.3f" $(echo "$BTCUSD*($COINBASE - $BLOCKREWARD) / $TXCOUNT " | bc -l)) "USD"

# fee estimates
echo "estimated fee for inclusion in..."
for i in $(seq 2 8)
do
    ESTIMATE=$(bitcoin-cli estimatefee $i)
    FEE=$(printf "%02.2f" $(echo $ESTIMATE*$BTCUSD | bc))
    echo -e "\t$i blocks: $ESTIMATE BTC, $FEE USD"
done

echo "tx in mempool: " $(bitcoin-cli getmempoolinfo | jq '.size') ", usage:" $(($(bitcoin-cli getmempoolinfo | jq '.usage') /1024/1024)) " Mb, size:" $(($(bitcoin-cli getmempoolinfo | jq '.bytes') /1024/1024)) " Mb"
