#!/usr/bin/env bash

# (c) /u/supert 2016
# released under MIT licence

# monitor incoming blocks

POLLDELAY=10
NOHEADER=
DATEFMT="+%H:%M:%S~%Y-%m-%d" 

source script_functions

# test for options
while getopts hrd: opt
do
    case "$opt" in
    (h) echo "usage: $0 ";;
    (d) POLLDELAY=$OPTARG;;
    (r) NOHEADER=1;;
    esac
done

shift $((OPTIND - 1))

print_table_header $NOHEADER

LASTHASH=
NEWHASH=$(bitcoin-cli getbestblockhash)
NEWBLOCK=/tmp/lastblock-$RANDOM.tmp
TX=/tmp/tx-$RANDOM.tmp

# starting from last block, work back
while :
do
    if [ "$NEWHASH" != "$LASTHASH" ]
    then
        # new block
        print_block $NEWHASH
        LASTHASH=$NEWHASH
    else
        # same block
        sleep $POLLDELAY
    fi
    NEWHASH=$(bitcoin-cli getbestblockhash)
done
